### Create a new user
POST http://localhost:4000/api/v1/mysql/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe 2",
    "email": "jane.doe2@example.com",
    "roles": "admin",
    "status": "active"
}

### Get all users
GET http://localhost:4000/api/v1/mysql/users HTTP/1.1

### Get a user by ID
# Replace '1' with an actual user ID
GET http://localhost:4000/api/v1/mysql/users/1 HTTP/1.1

### Update a user
# Replace '1' with an actual user ID
PUT http://localhost:4000/api/v1/mysql/users/20 HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "status": "inactive"
}

### Delete a user
# Replace '1' with an actual user ID
DELETE http://localhost:4000/api/v1/mysql/users/45 HTTP/1.1

### Search for users
# Searches in name, email, and id fields
GET http://localhost:4000/api/v1/mysql/users/search?name=Hasan&email=munira@gmail.com HTTP/1.1



##PostGresql

### Create a new user
POST http://localhost:4000/api/v1/postgres/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe 2",
    "email": "jane.doe2@example.com",
    "password": "200720"
}

### Get all users
GET http://localhost:4000/api/v1/postgres/users HTTP/1.1

### Get a user by ID
# Replace '1' with an actual user ID
GET http://localhost:4000/api/v1/postgres/users/487e70d5-dbfa-4d1a-9150-062ef3c92f86 HTTP/1.1

### Update a user
# Replace '1' with an actual user ID
PUT http://localhost:4000/api/v1/postgres/users/487e70d5-dbfa-4d1a-9150-062ef3c92f86 HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "status": "inactive"
}

### Delete a user
# Replace '1' with an actual user ID
DELETE http://localhost:4000/api/v1/postgres/users/487e70d5-dbfa-4d1a-9150-062ef3c92f86 HTTP/1.1

### Search for users
# Searches in name, email, and id fields
GET http://localhost:4000/api/v1/postgres/users/search?name=Hasan HTTP/1.1

###
